version: "3.8"
services:
  frontend:
    container_name: todoapp_frontend
    build: ./src/frontend/
    depends_on:
      - backend
    volumes:
      - ./src/frontend/src:/app/src
    ports:
      - 4201:4201
  backend:
    container_name: todoapp_backend
    build: ./src/backend/
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 5555:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__TodoAppDbConnection=Host=database;Port=5432;Database=todoapp;Username=postgres;Password=postgres"
      - "Cors__AllowedOrigins__0:http://localhost:4201"
  database:
    container_name: todoapp_database
    image: postgres:13
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
volumes:  
  pgdata:
